# application: mnemonic-official-py3
# version: beta

runtime: python312
entrypoint: uvicorn main:app --port=${PORT} --no-access-log

handlers:
- url: /favicon\.ico
  static_files: dist/favicon.ico
  upload: favicon\.ico
- url: /ads\.txt
  static_files: dist/ads.txt
  upload: ads\.txt
- url: /admin/api/(.+)
  script: auto
  secure: always
- url: /(api|task)/(.+)
  script: auto
  secure: always
- url: /(.+)\.(txt|css|js|png|svg|jpg|gif|eot|ttf|woff)
  static_files: dist/\1.\2
  upload: dist/(.+)
  secure: always
- url: /(.+)?
  static_files: dist/index.html
  upload: dist/index\.html
  secure: always
  http_headers:
    Strict-Transport-Security: max-age=31536000; includeSubDomains
    X-Frame-Options: DENY
